### ISSUE TITLE
hsweb-iot-cloud widows7开发环境部署

### ISSUE THREAD

**Issue by 453514644** [hs-web/hsweb-iot-cloud#6]
hsweb-iot-cloud开发环境如何部署，有没有部署文档给参考下？在qq群里发了但没有回复，非常感谢

**Comment by 453514644** [comment]
也愿意为hsweb-iot-cloud贡献一份力量

**Comment by zhou-hao** [comment]
windows上安装 redis,zookeeper,kafka 就行了。 安装方法百度一下吧。

**Comment by 453514644** [comment]
你好，kafka进入到bin/windows目录下运行下面语句一直“系统找不到指定路径，但文件确实存在” 启动kafka并指定配置文件

kafka-server-start.bat ../../config/server.properties

**Comment by zhou-hao** [comment]
写绝对路径试试
